# Generated by Django 2.0.13 on 2019-09-29 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expired_date',
            field=models.DateField(default=datetime.date(2019, 10, 29)),
        ),
    ]
