# Generated by Django 2.0.13 on 2019-05-03 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expired_date',
            field=models.DateField(default=datetime.date(2019, 6, 2)),
        ),
    ]
